# -*- coding: utf-8 -*-
"""Atividade MatPlotLib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rfA5fc9G3dJqKms0pcmNsOkKhwvWGLj
"""

!pip install matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

"""> 1) Plote um gráfico para cada conjunto de dados abaixo:


> Conjunto 1:
* linha => Pontilhada
* Cor => Verde
* Marcador => Pixel
* Rótulos em X e Y

> Conjunto 2:
* Rótulos "Anos", "População A(milhões)" e "População B(milhões)
* legenda


"""

print("Conjunto 1:")
X = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio"]
Y = [2000, 2500, 3000, 2800, 3500]
fmt = 'g--.'

plt.plot(X, Y, fmt)
plt.xlabel("Mês")
plt.ylabel("Venda")
plt.show()

print("Conjunto 1:")
X = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio"]
Y = [2000, 2500, 3000, 2800, 3500]

width = 0.2
index = np.arange(5)

plt.bar(index, Y, width=width)
plt.xlabel("Mês")
plt.ylabel("Venda")
plt.xticks(index, X)
plt.show()

print("Conjunto 1:")
X = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio"]
Y = [2000, 2500, 3000, 2800, 3500]


plt.pie(Y, labels=X, autopct="%.2f%%", shadow=True);
plt.show()

print("Conjunto 1:")
mes = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio"]
vendas = [2000, 2500, 3000, 2800, 3500]

sns.barplot(x=mes, y=vendas, hue=mes, palette="viridis")
plt.xlabel('Mês')
plt.ylabel('Vendas')
plt.xticks(rotation=45)
plt.show()

print("Conjunto 2:")
data = {"Anos": [2010, 2011, 2012, 2013, 2014, 2015, 2016],
        "População A": [112, 115, 118, 121, 124, 127, 131],
        "População B": [105, 108, 111, 114, 117, 128, 132]}

popl = pd.DataFrame(data)

plt.plot(popl["Anos"], popl["População A"])
plt.plot(popl["Anos"], popl["População B"])
plt.xlabel("Anos")
plt.ylabel("População")
plt.title("Crescimento populacional durante os anos")
plt.legend(["População A (milhões)", "População B (milhões)"])
plt.show()

print("Conjunto 2:")
data = {"Anos": [2010, 2011, 2012, 2013, 2014, 2015, 2016],
        "População A": [112, 115, 118, 121, 124, 127, 131],
        "População B": [105, 108, 111, 114, 117, 128, 132]}

popl = pd.DataFrame(data)

width = 0.2
index = np.arange(7)

plt.bar(index, popl['População A'], width=width, label="População A")
plt.bar(index + width, popl['População B'], width=width, label="População B")
plt.xlabel("Ano")
plt.ylabel("População")
plt.xticks(index + width / 2, popl['Anos'])
plt.ylim([0,150])
plt.legend(["População A (milhões)", "População B (milhões)"])
plt.show()