# -*- coding: utf-8 -*-
"""biblioteca Github

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cO4CNaM3K3mVOrwcyKl90wgsLkci2uTS
"""

! git clone https://github.com/Hrushikesh-github/animal-3.git

import requests

url = "https://raw.githubusercontent.com/Hrushikesh-github/animal-3/master/README.md"
response = requests.get(url)
texto = response.text
print(texto)

import pandas as pd

url ="https://raw.githubusercontent.com/datamagic2020/SampleDataStore/main/height_weight_dataset1.csv"
arquivo_csv = pd.read_csv(url)
print(arquivo_csv.head())

!wget https://raw.githubusercontent.com/Hrushikesh-github/animal-3/master/cats/cats_00001.jpg -O /content/gato.png

!curl -o /content/cachorro.png https://raw.githubusercontent.com/Hrushikesh-github/animal-3/master/dogs/dogs_00001.jpg

import cv2

img_com_open_cv = cv2.imread('/content/gato.png')

from google.colab.patches import cv2_imshow
cv2_imshow(img_com_open_cv)

from PIL import Image

img_com_PIL = Image.open('/content/cachorro.png')

img_com_PIL.show()
display(img_com_PIL)