# -*- coding: utf-8 -*-
"""Dicas de sintaxe do Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wz1XqWGU4hhmIu01xzWSdmrZZAS5fZ2C

# Dicas de sintaxe do Python

Quer aprender Python, mas não sabe por onde começar? Esse tutorial foi feito para você. Ele é baseado em uma tradução do notebook [Python syntax cheat sheet](https://github.com/ireapps/teaching-guide-intro-to-pandas/blob/master/Python%20syntax%20cheat%20sheet.ipynb), que foi revisada e expandida pela Escola de Dados.

Aqui, focaremos em conhecimentos básicos sobre a linguagem.

Seguiremos as seguintes etapas:

- Usando notebooks
- Tipos embutidos
    - Strings
    - Números e operações matemáticas
    - Booleanos
- Atribuição de variável
- Métodos de string
- Comentários
- A função `print()`
- Coleções de dados
    - Listas
    - Dicionários
- Estrutura de repetição `for`
- Declarações `if`

Pronto? Vamos lá!

# Usando notebooks

Há muitas maneiras de escrever e rodar um código Python no seu computador. Uma delas - o método que estamos usando aqui - é usar os notebooks, que nada mais são do que documentos interativos que permitem escrever códigos, executá-los e ver os resultados. Tudo no mesmo lugar.

Notebooks podem ser utilizados online. É o caso, por exemplo, do [Google Colab](https://colab.research.google.com/) ou do site do [Jupyter](https://jupyter.org/try). Também é possível trabalhar com eles de forma offline, mas diretamente do seu navegador, com o [Jupyter Notebook](https://jupyter.org/). Outra opção ainda é usar algum outro programa que tenha suporte a notebooks, como o [Visual Studio Code](https://code.visualstudio.com/).

Os notebooks são muito úteis para análise de dados, pois permitem deixar seu código bem documentado, com explicações sobre o que acontece em cada etapa do processo. Além de códigos, você pode incluir textos (como este que você está lendo) no formato "markdown". Você pode encontrar exemplos de notebook em alguns de nossos [tutoriais da Escola de Dados](https://escoladedados.org/tutoriais/), como este sobre [cruzar dados de desmatamento e agropecuária usando Python](https://escoladedados.org/tutoriais/dados-de-desmatamento-e-agropecuaria-python/).

Basicamente, o funcionamento de um notebook consiste em incluir novas células e executá-las.

*  **Para adicionar uma nova célula**:
    * Jupyter Notebook:  Clique no ícone  `+` embaixo do menu `File` e escolha se quer texto (markdown) ou código (Code) no menu suspenso embaixo do menu `Widgets`.
    * Google Colab: Clique em `+ Código` ou `+ Texto`, embaixo do menu `Arquivo`.

*  **Para executar uma célula de código:** Pressione `Shift` + `Enter`.

## Erros comuns

**Não executar as células**: O notebook não "sabe" o código que está na célula até que ele seja executado. Por exemplo, se você definir uma variável chamada `meu_nome` em uma célula e depois tentar acessar essa mesma variável em outra célula sem executar a célula que contém a variável antes, você receberá um erro: `NameError: name 'meu_nome' is not defined`.

A solução é simplesmente rodar a célula onde está a variável. Repare que ao lado de cada notebook há um número, que indica a ordem de execução das células.

**A célula "congela" em alguma execução**: Se ao executar uma célula, ela fica rodando "para sempre", com um sinal de `*` no lugar do número que indica a ordem de execução, então, provavelmente aconteceu alguma destas possibilidades: o código de fato leva muito tempo para ser executado, entrou em um loop infinito ou o "kernel" (que é como o "cérebro" do notebook, que de fato interpreta e executado os comandos) travou e será preciso reiniciá-lo. Neste caso, você pode clicar no botão com o símbolo quadrado de "stop" ou reiniciar o kernel.

# Tipos embutidos

Assim como Excel e outros softwares de processamento de dados, Python reconhece uma gama de diferentes tipos de dados, sendo que três deles receberão mais ênfase aqui:

- Strings (texto)
- Números (inteiros ou `int`, números com casas decimais ou `float`, por exemplo)
- Booleanos (`True`(verdadeiro) e `False`(falso)).

Você pode usar a função embutida [`type()`](https://docs.python.org/pt-br/3/library/functions.html#type) para verificar o tipo de dado de um valor qualquer. Rode a célula abaixo para visualizar um exemplo:
"""

type(45)

"""# Strings

Uma string é um conjunto de caracteres - letras, números, acentos ou o que quer que seja - acompanhado de aspas simples ou duplas, não importando qual, contanto que as aspas de início e fim sejam iguais. O código nesse notebook usa aspas simples. O guia de estilo do Python não recomenda alternar entre aspas, ["escolha uma e vá com ela até o fim."](https://www.python.org/dev/peps/pep-0008/#string-quotes).

Rode a célula abaixo para ver um exemplo:
"""

'Olá Mundo!'

"Python é uma linguagem de programação"

"""Se a sua string possuir apostrófos ou citações, você tem duas opções para fazer o sinal. Execute as células para conferir:  

1. "Escapar" o caractere, colocando uma barra invertida (`\`) antes dele:
"""

"Já tomou um copo d\'água hoje?"

"""2.   Mudar as aspas simples para aspas duplas:"""

"Já tomou um copo d'água hoje?"

"""Na prática, as duas alternativas funcionam da mesma forma. Mas a segunda opção é mais recomendada.

Quando você chama a funcão `type()` em uma string, o Python irá lhe retornar `str`.
"""

type('Olá!')

"""Chamando a [função `str()`](https://docs.python.org/pt-br/3/library/stdtypes.html#str) em um valor qualquer, irá lhe retornar aquele mesmo valor convertido em string. Pode parecer que não muda nada, mas lembre-se que não é possível fazer operações matemáticas como substração, soma ou média com strings. É um erro comum na análise de dados tentar - sem sucesso - realizar operações do tipo em alguma coluna de uma base de dados, pois a variável apesar de ter números é interpretada como uma string."""

str(45)

"""Você pode utilizar uma função dentro de outra função:"""

type(str(45))

"""Também pode passar um valor boleano e a função identificará como string:"""

str(True)

"""Se você "adicionar" strings com um sinal de mais `+`, elas serão concatenadas:"""

'SEXTA' + '-' + 'FEIRA'

"""Agora que você já sabe disso, qual a diferença entre as duas células abaixo? E por que elas produzem resultados diferentes?"""

5+5

"5"+"5"

"""# Números e operações matemáticas

O Python reconhece diversos tipos de dados numéricos. Os dois mais comuns são:

*   integers (números inteiros)
"""

type(12)

"""*   floats (números com casas decimais)."""

type(12.4)

"""Assim como a função `str()` converte qualquer valor em string, chamar a função `int()` em um tipo de dado númerico (mesmo que este esteja no formato string) tentará forçá-lo a ser um inteiro."""

int(35.6)

int('45')

"""O mesmo acontece quando utilizamos a função `float()`."""

float(46)

float('45')

"""O Python permite realizar operações matemáticas das mais [básicas](https://www.digitalocean.com/community/tutorials/how-to-do-math-in-python-3-with-operators) até as mais [avançadas](https://docs.python.org/pt-br/3/library/math.html). Vejamos abaixo as quatro operações elementares em ação."""

4+2

10-9

5*10

1000/10

"""Para elevar um número à potência de outro número, utilize dois asterísticos `**`."""

5**2

"""# Booleanos

Assim como o Excel, que possui os tipos `VERDADEIRO` e `FALSO`, Python possui tipos booleanos. Eles são `True` e `False` -- perceba que eles não devem vir acompanhados de aspas e que apenas as iniciais devem ser maiúsculas.

Normalmente valores booleanos são retornados quando você está trabalhando com algum tipo de declaração condicional - comparando valores, verificando se uma string está dentro de outra string, se um valor está contido em uma lista, etc.
"""

type(False)

type(True)

"""Os [operadores lógicos do Python](https://docs.python.org/pt-br/3/reference/expressions.html#comparisons) são:

- `>` maior que
- `<` menor que
- `>=` maior que ou igual a
- `<=` menor que ou igual a
- `==` igual a
- `!=` diferente de

Repare que o símbolo de igual (`=`) é utilizado para declarar algum valor. Por exemplo. `ano = 2021` declara o número 2021 a uma variável (falaremos mais sobre elas em breve) chamada *ano*.

Mas quando utilizamos `==` é como se estivéssemos fazendo uma pergunta: isto é igual a aquilo?

Vejamos um exemplo abaixo. Primeiro, vamos declarar a variável `ano`, visualizá-la e depois usar o operador lógico `==`.
"""

ano = 2021

ano

ano == 1900

ano == 2021

"""Se a célula `ano == 1900` fosse executada com apenas um símbolo igual, ao invés de "perguntar" se a variável `ano` é igual 2021, estaríamos sobreescrevendo este número e atribuindo um novo valor (1900) a ela.

Abaixo, você encontra outros exemplos de operadores lógicos.
"""

4 > 6

4 < 6

"""Python é uma linguagem case sensitive, ou seja, a mesma palavra pode ser entendida como uma palavra diferente simplesmente porque uma letra está maiuscula ou minúscula."""

'Python' == 'python'

"""# Atribuição de variável

O sinal de igual (`=`) atribui um valor a uma variável. Pense em uma variável simplesmente como algo que... pode variar ou cujo valor poder mudar. Ou como uma etiqueta que tem algum valor atribuído a ela.

Por exemplo, eu posso declarar `nome = 'Maria Carolina Sousa Silva Santos Albuquerque'` e, se eu precisar utilizar este nome no futuro, ao invés de digitá-lo novamente, posso simplesmente chamar minha variável `nome`.

Nomes de variáveis podem ser qualquer coisa que nós quiseremos, mas existem algumas regras e convenções para serem seguidas:

- Eles devem começar apenas com letras ou traço baixo (underscore: `_`) e podem conter letras, *underscore* ou números;
- Os nomes são `case sensitives`. Ou seja, `Ano` é diferente de `ano`. Em geral, em Python, usamos os nomes das variáveis todos em minúsculas e com underscore para separar palavras quando necessário.
- Use nomes de variáveis que sejam descritivos e sigam estas convenções do mundo Python. Por exemplo, é melhor usar `ano_nascimento` do que `AnoNascimento` ou `AnNasc`.

Para saber mais sobre o assunto, você pode conferir este texto do [site The Hello World Program](https://thehelloworldprogram.com/python/python-variable-assignment-statements-rules-conventions-naming/) ou [esta explicação do Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-use-variables-in-python-3).
"""

meu_nome = 'Francisco'

meu_nome

meu_numero_preferido = 10 + 3

meu_numero_preferido

"""Também é possível fazer operações com variáveis:"""

times_da_nfl = 32
times_da_mlb = 30
times_da_nba = 30
times_da_nhl = 31

quantidade_de_times_profissionais = times_da_nfl + times_da_mlb + times_da_nba + times_da_nhl

quantidade_de_times_profissionais

"""# Métodos de string

Voltando a falar de strings, é importante ressaltar que esses objetos possuem uma série de [métodos](https://docs.python.org/pt-br/3/library/stdtypes.html#string-methods) muito úteis.

Vamos usar uma string como exemplo para ilustrar os mais comuns.
"""

minha_string = '    Oi, amigos!'
minha_string

"""Podemos usar um ponto após a variável e chamar uma função, que irá operar sobre ela. Veja o exemplo do `upper()`, que deixa todos os caracteres de uma string em caixa alta:"""

minha_string.upper()

"""`lower()` converte para minúsculos:"""

minha_string.lower()

"""`replace()` irá substituir um trecho de texto com outro trecho a ser especificado por você:"""

minha_string.replace('amigos', 'inimigos')

"""`count()` irá contar a quantidade de vezes que um caractere ou grupo de caracteres aparece na sua string:"""

minha_string.count('o')

"""`split()` irá fatiar a string e armazená-la em uma [lista](#Listas) (iremos falar mais sobre elas já já) baseado em um delimitador. Caso você não defina um delimitador, o delimitador definido por padrão é um espaço em branco:"""

minha_string.split()

minha_string.split(',')

"""Veja como a vírgula mudou de lugar no resultado da célula acima."""

minha_string.split('texto_inexistente_na_string')

"""A função `strip()` remove espaços em branco das extremidade da sua string (mas não os espaços em branco internos):"""

minha_string.strip()

"""Tem uma coisa muito incrível chamada "encadeamento de método" que te permite combinar métodos - é só adicioná-los um ao final do outro, com um ponto entre eles. Digamos que nós quiséssemos remover um espaço em branco da nossa string _e_ colocá-la em maiúsculo:"""

minha_string.strip().upper()

"""Perceba que `count()` diferencia entre minúsculas e maiúsculas. Se o que você deseja é contar todas as letras 'o', você deve converter sua string original para maiúscula ou minúscula anteriormente."""

minha_string.upper().count('O')

"""Veja que nossa string original permanece inalterada:"""

minha_string

"""Mas por que isso? É que a gente não atribuiu os resultados dessas operações a nenhuma variável. Uma prática muito comum, especialmente quando estamos limpando dados, é atribuir os resultados a uma nova variável:"""

minha_string_limpa = minha_string.strip().upper()

minha_string_limpa

"""# Comentários

Uma linha comentada - uma nota que você não quer que seja interpretada como código pelo Python - começa com um sinal de `#`. Esse recurso é utilizado para que você e outros colaboradores entendam o que está acontecendo naquele ponto do seu código e o porquê de estar acontecendo.

É recomendável usar esse recurso logo acima da linha de código que você deseja comentar:
"""

salario = 1021.34

# convertendo este valor para inteiro para eliminar as casas decimais
int(salario)

"""# A função `print()`

Até então, nós executamos as células deste notebook para pegar o último valor retornado pelo código que escrevemos. Usar a função [`print()`](https://docs.python.org/pt-br/3/library/functions.html#print) é uma forma de imprimir na tela coisas específicas do seu código. Esta é também uma ferramenta bem útil para depuração de código.

Para exibir múltiplos elementos na mesma linha, separe-os com uma vírgula.
"""

print('Olá!')

print(meu_nome)

print('Olá,', meu_nome)

"""# Coleções de dados

Agora iremos abordar duas maneiras que você pode usar Python para agrupar dados em uma coleção: listas e dicionários.

**Listas**

Uma _lista_ é um conjunto de itens separados por vírgulas dentro de colchetes: `[]`.

Aqui vai uma lista de ingredientes, cada um sendo uma string, que combinados formam a receita de um molho.
"""

ingredientes_para_o_molho = ['tomate', 'cebola', 'pimenta', 'limão', 'coentro']

"""Para acessar um item de uma lista você deve informar sua posição numérica na lista - o seu _índice_ (1, 2, 3, etc.) - dentro de colchetes imediatamente após o nome da variável da lista. Assim como em muitas outras linguagens de programação, em Python a contagem começa em 0. Isso significa que o primeiro item de uma lista é o item `0`."""

ingredientes_para_o_molho[0]

ingredientes_para_o_molho[1]

"""Você pode usar _índices negativos_ para acessar itens do lado direito da lista - e, na verdade, `[-1]` é um termo comum para acessar "o último item da lista"."""

ingredientes_para_o_molho[-1]

"""Se o que você precisa é pegar um trecho com alguns itens da sua lista, você só precisa usar dois pontos e definir o intervalo em questão.

Se quer acessar os primeiros três itens, por exemplo, é só fazer assim:
"""

ingredientes_para_o_molho[0:3]

"""Você poderia ter deixado de fora o 0 do começo - quando você não informa o primeiro número, o Python por padrão define para "o primeiro item na lista." Da mesma forma, se você deixar de fora o último número, o padrão definido pelo Python é "o último item da lista."
"""

ingredientes_para_o_molho[:3]

"""Observe que essa fatia nos devolve os itens 0, 1 e 2. O item 3 no nosso conjunto é o primeiro item que nós _não_ queremos. Isso pode parecer confuso em um primeiro momento. Vamos observar mais alguns exemplos:"""

# tudo na lista, exceto o item de número 0, ou seja, o primeiro
ingredientes_para_o_molho[1:]

# o segundo, terceiro e quarto itens
ingredientes_para_o_molho[1:4]

# os dois últimos itens
ingredientes_para_o_molho[-2:]

"""Para saber quantos itens uma lista tem é só usar a funcão `len()`"""

len(ingredientes_para_o_molho)

"""Para adicionar itens a uma lista, use o método `append()`:"""

ingredientes_para_o_molho

ingredientes_para_o_molho.append('areia')

ingredientes_para_o_molho

"""O único problema aqui é que nosso molho ficou meio nojento.

Para remover um item de uma lista, use o método `pop()`. Se você não informar o índice númerico do item específico que você quer remover, o valor padrão do método é o último item da lista.
"""

ingredientes_para_o_molho.pop()

ingredientes_para_o_molho

"""Você pode usar as expressões [`in` e `not in`](https://docs.python.org/pt-br/3/reference/expressions.html#membership-test-operations) para verificar se um item pertence àquela lista (e irá lhe retornar um booleano):"""

'limão' in ingredientes_para_o_molho

'coentro' not in ingredientes_para_o_molho

"""# Dicionários

Um dicionário é um conjunto de pares de chave/valor, separados por vírgula, dentro de chaves: `{}`. Vamos fazer uma receita inteira de molho:
"""

molho = {
    'ingredientes': ingredientes_para_o_molho,
    'instrucoes': 'Corte todos os ingredientes e cozinhe eles por um tempinho.',
    'porcoes': 12
}

"""Para retornar um valor de um dicionário, você deve chamar o nome da sua respectiva chave dentro de colchetes `[]` imediatamente após o nome da variável do dicionário em questão."""

molho['porcoes']

molho['ingredientes']

"""Para adicionar um novo conjunto de chave/valor a um dicionário, atribua uma nova chave dentro de colchetes ao dicionário desejado e defina o valor logo após o `=`:"""

molho['esta_uma_delicia'] = True

molho

"""Para excluir um par chave/valor de um dicionário, utilize o comando `del` antes o nome do dicionário acompanhado da chave específica:"""

del molho['esta_uma_delicia']

molho

"""# Indentação

Espaços em branco fazem MUITA diferença para o Python. Às vezes você precisará indentar pedaços de código para que as coisas funcionem. Isso pode ser confuso! `IndentationError` é um tipo muito comum de erro, até mesmo para programadores mais experientes. Inclusive, alguns editores de notebook podem ser prestativos e te dar uma mãozinha inserindo espaços em branco para você em alguns casos.

Você pode usar tabs ou espaços, só não misture os dois. [O guia de estilo do Python](https://www.python.org/dev/peps/pep-0008/) recomenda que você indente seu código com quatro espaços, então será isso o que nós usaremos.

# Estrutura de repetição `for`

Você deve usar um `for` para iterar sobre uma coleção de coisas.

Abaixo, nossa declaração começa com a palavra-chave `for` (em minúsculas), e então uma variável chamada `numero`. Você pode chamar essa variável como quiser. Então, insira a palavra-chave `in` e em seguida a coleção que você está percorrendo (ou o nome da sua variável), e então dois pontos. Após isso vamos colocar um bloco indentado de código com instruções sobre o que fazer com cada item na coleção.

Digamos que temos uma lista de números chamada `lista_de_numeros`.
"""

lista_de_numeros = [1, 2, 3, 4, 5, 6]

"""É possível percorer os elementos da lista e imprimir cada um deles na tela:"""

for numero in lista_de_numeros:
    print(numero)

"""Podemos também exibir na tela cada número da lista _multiplicado_ por 6:"""

for numero in lista_de_numeros:
    print(numero*6)

""" Observe que a escolha de nome da variável chamada de `numero` na sua repetição é totalmente aleatória. Muitas vezes, você irá ver uma expressão como `for i in alguma_lista`, por exemplo, mas qualquer coisa funcionaria no lugar do `i`. Veja:"""

for banana in lista_de_numeros:
    print(banana)

"""Talvez seja desafiador, em um primeiro momento, diferenciar o que é uma "palavra reservada do Python" e o que é o nome de uma variável que você pode definir. Isso, no entanto, vem com a prática.

Também dá pra iterar sobre os elementos de uma string. Vamos percorrer sobre as letras nesta sentença:
"""

sentenca = 'Olá, Sexta-Feira'

for letra in sentenca:
    print(letra)

"""Ou seja, strings são iteráveis, assim como listas, logo, você pode utilizar os mesmos métodos:"""

# pegue os primeiros cinco caracteres
sentenca[:5]

# descubra o tamanho da sentenca
len(sentenca)

'Olá' in sentenca

"""Você pode percorrer os elementos de um dicionário também - só tenha em mente que dicionários _não registram a ordem que os itens foram adicionados nele_.

Quando você está iterando sobre um dicionário, a variável que você colocou após o `for` irá remeter às chaves. Vamos percorrer sobre nosso dicionário `molho` ali de cima:
"""

for chave in molho:
    print(chave)

"""Para pegar o _valor_ do item de um dicionário em uma iteração você deve usar a chave:"""

for chave in molho:
    print(molho[chave])

"""# Declarações `if`

Assim como no Excel, você pode lançar mão da estrutura "SE" para lidar com lógica condicional.

No Python, essas declarações começam com a palavra-chave `if` (em minúsculas), a condição a ser avaliada, seguida de dois pontos, e então uma nova linha de bloco de código indentado para então executar o código, se a condição encontrada for `True` (verdadeira).
"""

if 4 < 6:
    print('4 é menor do que 6')

"""Você também pode adicionar um `else` com um bloco de código indentado caso a condição encontrada for `False` (falsa)."""

if 4 > 6:
    print('4 é maior do que 6?!')
else:
    print('4 não é maior do que 6.')

"""Se você precisar, você pode adicionar múltiplas condições com `elif`. Experimente alterar os resultados do placar e executar a célular para ver o código em funcionamento."""

NOSSO_PLACAR = 6
PLACAR_DO_OUTRO_TIME = 8

if NOSSO_PLACAR > PLACAR_DO_OUTRO_TIME:
    print('Ganhamos!')
elif PLACAR_DO_OUTRO_TIME < NOSSO_PLACAR:
    print('Empatamos!')
else:
    print('Perdemos!')

"""Agora que você entendeu como funciona a linguagem Python, já pode dar seus primeiros passos [aprendendo a biblioteca Pandas usando este notebook](Pandas.ipynb)"""