# -*- coding: utf-8 -*-
"""Folium

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3Lq5dKE2N-goCjeteaj7aY15rAFKxST
"""

!pip install folium

import folium

min_lon, max_lon = -45, -35
min_lat, max_lat = -25, -15

m = folium.Map(
    max_bounds=True,
    location=[-20, -40],
    zoom_start=6,
    min_lat=min_lat,
    max_lat=max_lat,
    min_lon=min_lon,
    max_lon=max_lon,
    control_scale=True,
    zoom_control=True,
    width=800,
    height=400,
)

folium.CircleMarker([max_lat, min_lon], tooltip="Upper Left Corner").add_to(m)
folium.CircleMarker([min_lat, min_lon], tooltip="Lower Left Corner").add_to(m)
folium.CircleMarker([min_lat, max_lon], tooltip="Lower Right Corner").add_to(m)
folium.CircleMarker([max_lat, max_lon], tooltip="Upper Right Corner").add_to(m)

m

m = folium.Map(tiles=None,
               width=800,
              height=400,)

folium.TileLayer("OpenStreetMap").add_to(m)
folium.TileLayer(show=False, control=True).add_to(m)

fg = folium.FeatureGroup(name="Icon collection", show=False).add_to(m)
folium.Marker(location=(0, 0)).add_to(fg)

folium.LayerControl().add_to(m)

m

import folium


m = folium.Map([45, 0], zoom_start=4,
               width=800, height=400)

folium.Marker([45, -30], popup="inline implicit popup").add_to(m)

folium.CircleMarker(
    location=[45, -10],
    radius=25,
    fill=True,
    popup=folium.Popup("inline explicit Popup"),
).add_to(m)

ls = folium.PolyLine(
    locations=[[43, 7], [43, 13], [47, 13], [47, 7], [43, 7]], color="red"
)

ls.add_child(folium.Popup("outline Popup on Polyline"))
ls.add_to(m)

gj = folium.GeoJson(
    data={"type": "Polygon", "coordinates": [[[27, 43], [33, 43], [33, 47], [27, 47]]]}
)

gj.add_child(folium.Popup("outline Popup on GeoJSON"))
gj.add_to(m)

m

import folium

lon, lat = -38.625, -12.875
zoom_start = 8
folium.Map(location=[lat, lon], tiles=" ", zoom_start=zoom_start)

import folium


m = folium.Map(location=[22.5, -115], zoom_start=4)

video = folium.raster_layers.VideoOverlay(
    video_url="https://www.mapbox.com/bites/00188/patricia_nasa.webm",
    bounds=[[32, -130], [13, -100]],
    opacity=0.65,
    attr="Video from patricia_nasa",
    autoplay=True,
    loop=False,
)

video.add_to(m)

m

import folium

map_geo = folium.Map(location=[47.46901, 9.36688], zoom_start=13,
                     width=800, height=400)

folium.raster_layers.WmsTileLayer(url = 'https://wms.geo.admin.ch/?',
                                  layers = 'ch.bfe.fernwaerme-nachfrage_wohn_dienstleistungsgebaeude',
                                  transparent = True,
                                  control = True,
                                  fmt="image/png",
                                  name = 'energy',
                                  overlay = True,
                                  show = True,
                                  ).add_to(map_geo)
folium.LayerControl().add_to(map_geo)

map_geo

lat = +38.89399
lon = -77.03659
zoom_start = 17

m = folium.Map(location=[lat, lon], zoom_start=zoom_start,
               width=800, height=400)

kw = {"color": "red", "fill": True, "radius": 20}

folium.CircleMarker([38.89415, -77.03738], **kw).add_to(m)
folium.CircleMarker([38.89415, -77.03578], **kw).add_to(m)


locations = [
    [
        (38.893596444352134, -77.03814983367920),
        (38.893379333722040, -77.03792452812195),
    ],
    [
        (38.893379333722040, -77.03792452812195),
        (38.893162222428310, -77.03761339187622),
    ],
    [
        (38.893162222428310, -77.03761339187622),
        (38.893028615148424, -77.03731298446655),
    ],
    [
        (38.893028615148424, -77.03731298446655),
        (38.892920059048464, -77.03691601753235),
    ],
    [
        (38.892920059048464, -77.03691601753235),
        (38.892903358095296, -77.03637957572937),
    ],
    [
        (38.892903358095296, -77.03637957572937),
        (38.893011914220770, -77.03592896461487),
    ],
    [
        (38.893011914220770, -77.03592896461487),
        (38.893162222428310, -77.03549981117249),
    ],
    [
        (38.893162222428310, -77.03549981117249),
        (38.893404384982480, -77.03514575958252),
    ],
    [
        (38.893404384982480, -77.03514575958252),
        (38.893596444352134, -77.03496336936950),
    ],
]

folium.PolyLine(
    locations=locations,
    color="orange",
    weight=8,
    opacity=1,
    smooth_factor=0,
).add_to(m)

m

import folium
from folium import plugins

coordenadas = []


mapa_linhas = folium.Map(location = [-17.97577, -47.79637], zoom_start = 11, control_scale = True,
                         tiles = "cartodbpositron")

folium.Marker(location = [-18.1721,  -47.9415],
              popup = "St. Therese Community Centre, 17 Conrod Rd.",
              icon = folium.Icon(icon = "glyphicon glyphicon-home",
                                 color = "darkred",
                                 icon_color = "white",
                                 prefix = "glyphicon")).add_to(mapa_linhas)

folium.Marker(location = [-18,17255545, -47,9259623],
              popup = "1st Water Station",
              icon = folium.Icon(icon = "glyphicon glyphicon-glass",
                                 color = "darkblue",
                                 icon_color = "white",
                                 prefix = "glyphicon")).add_to(mapa_linhas)


for i in range(len(coordenadas)-1):
    folium.PolyLine(locations = [[coordenadas[i][0], coordenadas[i][1]], [coordenadas[i+1][0], coordenadas[i+1][1]]],
                   color = 'navy').add_to(mapa_linhas)

mapa_linhas.add_child(folium.LatLngPopup())

mapa_linhas

m = folium.Map((52, 0), tiles='cartodbpositron', zoom_start=8,
               width=800, height=400,
               control_scale=True)

fg1 = folium.FeatureGroup().add_to(m)
folium.Marker((52, 5), popup="inicial").add_to(fg1)

fg2 = folium.FeatureGroup(show=False).add_to(m)
folium.Marker((52, 5.1), popup="escondido").add_to(fg2)

folium.FitOverlays().add_to(m)

folium.LayerControl().add_to(m)

m

folium.Map().add_child(
    folium.ClickForMarker("<b>Lat:</b> ${lat}<br /><b>Lon:</b> ${lng}")
)

folium.Map().add_child(
    folium.LatLngPopup()
)

folium.Map().add_child(
    folium.ClickForLatLng(format_str='"[" + lat + "," + lng + "]"', alert=True)
import geopandas

gdf = geopandas.read_file(url))

m = folium.Map([43, -100], zoom_start=4,
                width=800, height=400)

url = "https://raw.githubusercontent.com/python-visualization/folium-example-data/main/us_states.json"

folium.GeoJson(url, zoom_on_click=True, style_function=lambda feature: {
        "fillColor": "green"
        if "e" in feature["properties"]["name"].lower()
        else "#ffff00",
        "color": "black",
        "weight": 2,
        "dashArray": "5, 5",
    }).add_to(m)

m

import pandas

state_data = pandas.read_csv(
    "https://raw.githubusercontent.com/python-visualization/folium-example-data/main/us_unemployment_oct_2012.csv"
)

m = folium.Map([43, -100], zoom_start=4,
               width=800, height=400)

choropleth = folium.Choropleth(
    geo_data=us_states,
    data=state_data,
    columns=["State", "Unemployment"],
    key_on="feature.id",
    fill_color="YlGn",
    name="Unemployment",
    show=False,
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

m